### PR TITLE
 Remove bundletool check that resources should not be directly under res/

### PR DESCRIPTION
**Pull request by JingYeoh**
Remove bundletool check that resources should not be directly under res/, read resources directory path from resourceTable.

### CODE REVIEW

**Comment by JingYeoh** [comment]
@googlebot I signed it!

**Comment by JingYeoh** [comment]
i think resources directory should be readed from resources.arsc, and i add junit test code for this, please review the code, if you have any question, please let me know.

**Comment by JingYeoh** [comment]
i found some error, and i will reopen it after the error is solved.

**Comment by plecesne** [comment]
I don't think this is a desirable feature in the App Bundle. In the APK, yes, but not in the App Bundle. Having resources under "res" allows us to make some validation, thus ensuring that developers don't accidentally add resources that are not referenced in the resource table.

**Pull request closed without merging**
